---
- hosts: servers
  remote_user: root
  gather_facts: no
  vars_files: 
   - varfile.yml


  tasks:
    - name: Create a logical volume
      shell: "lvcreate -l {{size}} -n {{logicalvol}} {{volgroup}} {{pvlocation}} {{physicalextentsize}} "


