---
- hosts: servers
  remote_user: root
  gather_facts: no

  tasks:
    - name: Create the backend disks, skips if present
      file:
        path= /mnt/brick1/b1
        state = directory

    - name: Mount the volumes
      mount:
        path = /mnt/brick1/b1
        src = /dev/volgrp1/logicalvol1
        fstype = xfs
        state = present
