---
- hosts: servers
  remote_user: root
  gather_facts: no
  vars_files: 
   - varfile.yml

  tasks:
    - name: Create a volume group
      shell: vgcreate {{diskcount}} {{disktype}} {{stripesize}} {{dalign}} {{volgroup}} {{pvlocation}}
      

...